kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: paychat-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:9.5
          ports:
            - name: tcp
              containerPort: 5432
          resources:
            requests:
              cpu: 0.01
              memory: "50Mi"
            limits:
              cpu: 2
              memory: "2Gi"
          env:
            - name: POSTGRES_USER
              value: paychat
            - name: POSTGRES_PASSWORD
              value: paychat
            - name: POSTGRES_DB
              value: paychat_production