default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
  <<: *default
  database: paychat_dev

test:
  <<: *default
  database: paychat_test

production:
  <<: *default
  database: paychat_production